version: '2'
services:
  chatbot:
    container_name: chatbot
    image: chbb-chatbot
    entrypoint: sh /usr/app/src/init.sh ${MODE}
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      PORT: 3000
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: bb

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bb
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"